Story/sus 15
diging/sustainability-db pull request #13
Opened 2018-11-14 17:55 UTC by namrathaov

Changed URI in search page to display title and year by loading dynamically.

2018-11-14 18:10 UTC, jdamerow requested changes

2018-11-14 18:10 UTC, jdamerow commented on sustainability/src/main/java/edu/asu/diging/sustainability/web/search/ResearcherSearchController.java
> +            logger.error("Resource " + uri + " is not a valid one.");
don't swallow the exception!

2018-11-14 18:10 UTC, jdamerow commented on sustainability/src/main/java/edu/asu/diging/sustainability/web/search/ResearcherSearchController.java
> +        Map<String, List<IAnnotation>> URIList =
variable names **never** start with a capital letter except when they are constants!

2018-11-14 18:10 UTC, jdamerow commented on sustainability/src/main/java/edu/asu/diging/sustainability/web/search/ResearcherSearchController.java
> +                logger.error("Resource " + uri + " is not a valid one.");
don't swallow the exception!

2018-11-14 18:10 UTC, jdamerow commented on sustainability/src/main/webapp/WEB-INF/tiles-defs.xml
> +	<definition name="perspective/researcher/resource" extends="base.definition">
why did you add that here. this endpoint doesn't return a jsp.

2018-11-14 18:10 UTC, jdamerow commented on sustainability/src/main/webapp/WEB-INF/views/search/results.jsp
> +					          "<a href = '<c:url value = '/text?uri = " + rsrc.uri + "'/>'>"
this cannot work. did you test that? c:url is a jsp expression evaluated server-side. at this point you do some javascript which is client-side.

2018-11-14 18:10 UTC, jdamerow commented on sustainability/src/main/webapp/WEB-INF/views/search/results.jsp
> +			                      + rsrc.title + " - " +	rsrc.year + "</a></li>";
years should be in parentheses like everywhere else.

2018-11-14 18:10 UTC, jdamerow commented on sustainability/src/main/webapp/WEB-INF/views/search/results.jsp
> +					  success: function (rsrc) {
what happens if the controller returns null?

2018-11-14 18:10 UTC, jdamerow commented on sustainability/src/main/webapp/WEB-INF/views/search/results.jsp
> +				    });
formatting is all over the place

2018-11-15 19:14 UTC, namrathaov commented
[SUS-15] Minor fixes, exception handling and formatting.

2018-11-15 21:45 UTC, jdamerow requested changes

2018-11-15 21:45 UTC, jdamerow commented on sustainability/src/main/java/edu/asu/diging/sustainability/web/search/ResearcherSearchController.java
> +                logger.error("Resource " + uri + " is not a valid one.");
not addressed

2018-11-15 21:45 UTC, jdamerow commented on sustainability/src/main/java/edu/asu/diging/sustainability/web/search/ResearcherSearchController.java
> +    @ResponseBody
remove. shouldn't be necessary anymore if you return a response entity

2018-11-15 21:45 UTC, jdamerow commented on sustainability/src/main/java/edu/asu/diging/sustainability/web/search/ResearcherSearchController.java
> +            logger.error("Resource " + uri + " is not a valid one.");
not addressed

2018-11-15 21:45 UTC, jdamerow commented on sustainability/src/main/webapp/WEB-INF/views/search/results.jsp
> +						  else if(rsrc.updatedOn == null){
why do you have an extra if here? is there another option besides == null or != null?

2018-11-15 21:45 UTC, closed without merging