Story/sus 1
diging/sustainability-db pull request #2
Opened 2018-10-25 17:27 UTC by namrathaov

Concepts page has a link to edit configuration.
Created a new JSP page to edit configuration with checkboxes.

2018-10-25 18:04 UTC, jdamerow requested changes
where is the configuration stored?

2018-10-25 18:04 UTC, jdamerow commented on sustainability/src/main/java/edu/asu/diging/sustainability/web/ListConceptController.java
> +    public String configuration(Model model) {
needs to have its own controller (roughly one controller per page)

2018-10-25 18:04 UTC, jdamerow commented on sustainability/src/main/java/edu/asu/diging/sustainability/web/ListConceptController.java
> +        model.addAttribute("concepts", concepts);
merge with line 62

2018-10-25 18:04 UTC, jdamerow commented on sustainability/src/main/java/edu/asu/diging/sustainability/web/ListConceptController.java
> +        roles.add("Practitioner");
these need to come from somewhere configurable, not hardcoded.

2018-10-25 18:04 UTC, jdamerow commented on sustainability/src/main/webapp/WEB-INF/views/admin/concepts/configuration.jsp
> +	            <input type="checkbox" class="default" name="${role}" value="${role}"> ${role}
name and value should be different (value can change over time as stakeholders change their mind, values need to stay the same in most cases for backwards compatibility).

2018-10-25 18:05 UTC, closed without merging

2018-10-26 17:32 UTC, namrathaov commented
I mistook that this ticket was only for designing the UI of the page. I will work on storing it.