Story/sus 13
diging/sustainability-db pull request #21
Opened 2018-11-28 17:41 UTC by namrathaov

[SUS-13] Added alias for concept name in edit configuration page and search page.

2018-11-28 17:47 UTC, jdamerow requested changes

2018-11-28 17:47 UTC, jdamerow commented on sustainability/src/main/java/edu/asu/diging/sustainability/core/service/impl/ConceptManager.java
> +    public void storeConceptAlias(String conceptId, String alias) {
merge with 'storeConceptSearchCategories'. no reason there would be an extra method for bot properties if there could just be one update method.

2018-11-28 17:47 UTC, jdamerow commented on sustainability/src/main/java/edu/asu/diging/sustainability/core/service/impl/ConceptManager.java
> +    public void storeConceptAlias(String conceptId, String alias) {
also, let's write some tests at least for the update method.

2019-01-15 18:58 UTC, namrathaov commented
Merged search categories and alias in one function. 
Added unit test for update function in Concept manager.

2019-01-15 19:31 UTC, jdamerow requested changes

2019-01-15 19:31 UTC, jdamerow commented on sustainability/src/test/java/edu/asu/diging/sustainability/core/service/impl/ConceptManagerTest.java
> +        verify(conceptRepo).save(concept);
you probably want to make sure category list and alias are updated

2019-01-15 19:31 UTC, jdamerow commented on sustainability/src/test/java/edu/asu/diging/sustainability/core/service/impl/ConceptManagerTest.java
> +    private Concept concept = new Concept();
no reason to make concept and categoryList class variables

2019-01-17 18:36 UTC, namrathaov commented
Updated test case to verify search category and alias are updated.

2019-01-18 20:48 UTC, jdamerow commented
ok to test

2019-01-18 20:51 UTC, jdamerow approved these changes

2019-01-18 20:51 UTC, merged